### PR TITLE
internal/be-shibboleth-missing-headers-wrong-redirection

### PR DESCRIPTION
**Pull request by milanmajchrak**
| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0.5  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |

### CODE REVIEW

**Review by MajoBerger — APPROVED** [review]

**Comment by MajoBerger** [comment]
What are those failing tests?

**Comment by milanmajchrak** [comment]
> What are those failing tests?

Where are failing tests?

**Comment by MajoBerger** [comment]
I noticed it here, it still shows under checks, but in this conversation it is green...
image

**Comment by MajoBerger** [comment]
those were probably old checks. Feel free to merge.

**Pull request merged**
